### ISSUE TITLE
build_config.mk not found

### ISSUE THREAD

**Issue by kosciuk** [zeitcoin/zeitcoin#8]
/bin/sh: 1: ./build_detect_platform: Permission denied
Makefile:18: build_config.mk: No existe el archivo o el directorio
make[1]: **\* No rule to make target 'build_config.mk'.  Stop.

**Comment by ovpn-to** [comment]
not a bug. 

cd src/
cd leveldb/
chmod +x build_detect_platform

and run make again

**Comment by fabdu43** [comment]
thanks  lol  2018

**Comment by Miladinho** [comment]
@fabdu43 

Why is the directory restricted by default? Is there a specific reason?

**Comment by Manikantad6** [comment]
hey guys please help, even after changing the permissions, i am getting the same issue permission denied
wht to do?
